In [ ]:
c ='atiq khan'
print(c)

In [ ]:
c =str()
c

In [ ]:
c =str('khan')
c

In [ ]:
a = 'Islambad'
print(a)

In [ ]:
a[0]

In [ ]:
a[0:4:2]

In [ ]:
a[:]

In [ ]:
del c
print(c)

In [ ]:
'islamabad' == 'islamabad'

In [ ]:
'islamabad' == 'Bannu'

In [ ]:
b = 'Bannu'
print(a + '-' + b)

In [ ]:
a * b

In [ ]:
for i in a:
    print(i)

In [ ]:
'I' not in a

In [ ]:
len(a)

In [ ]:
a.capitalize()
print(a)

In [35]:
a = 'islamabad'
a.upper()
print(a)

islamabad


In [38]:
'it''s raning today'.title()

'Its Raning Today'

In [43]:
b= 'khan atiq'

In [40]:
b.upper()

'KHAN'

In [41]:
b.lower()

'khan'

In [44]:
b.swapcase()

'KHAN ATIQ'

In [46]:
'AtIq kHaN'.swapcase()

'aTiQ KhAn'

In [49]:
'it''s' 'raning today'.find('o')

11

In [50]:
'My Name is {}, And i am form'.format('Atiq','Bannu')

'My Name is Atiq, And i am form'

In [52]:
'flat20'.isalnum()

True

In [56]:
'Atiq12'.isalpha()

False

In [58]:
'11'.isdigit()

True

In [59]:
'11.1'.isdecimal()

False

In [67]:
a = 'Hello my name is atiq'
a.split('is')

['Hello my name ', ' atiq']

In [70]:
'is'.join(['Hello my name ', ' atiq'])

'Hello my name is atiq'

In [71]:
a.replace('hello','Gretings')

'Hello my name is atiq'

In [72]:
'hello my name is atiq'.replace('atiq','khan')

'hello my name is khan'

In [76]:
n ='             khan         '
print(n) 

             khan         


In [77]:
n.strip()

'khan'

### List

In [1]:
l= {}
l

{}

In [4]:
l = {'atiq',1,1.1,True,3+6j}
l

{(3+6j), 1, 1.1, 'atiq'}

In [5]:
l = {1,'atiq','khan',2.2,True}
l

{1, 2.2, 'atiq', 'khan'}

In [6]:
a = list('Food')
a

['F', 'o', 'o', 'd']

In [7]:
a[0]

'F'

In [8]:
a[3]

'd'

In [9]:
a[-1]

'd'

In [10]:
a[0:2]

['F', 'o']

In [11]:
a[:-2]

['F', 'o']

In [12]:
a[::-1]

['d', 'o', 'o', 'F']

In [14]:
a = [1,2,3,4,[5,6,7]]
a

[1, 2, 3, 4, [5, 6, 7]]

In [16]:
a[4]

[5, 6, 7]

In [17]:
x = a[4]
x[1]

6

In [18]:
a[-1]

[5, 6, 7]

In [20]:
a[3]=3
print(a)

[1, 2, 3, 3, [5, 6, 7]]


In [24]:
a[0:4]=100,200,300,400,500,600
print(a)

[100, 200, 300, 400, 500, 600, 500, [5, 6, 7]]


In [25]:
len(a)

8

In [26]:
s = [1,2,3,4,5]
s

[1, 2, 3, 4, 5]

In [28]:
s.append(7)
print(s)

[1, 2, 3, 4, 5, 7]


In [32]:
s.extend([8,9])
print(s)

[1, 2, 3, 4, 5, 7, 8, 9]


In [34]:
s.insert(1,'atiq')
print(s)

[1, 'atiq', 'aiter', 2, 3, 4, 5, 7, 8, 9]


In [35]:
del (a)

In [37]:
del (s[2])
print(s)

[1, 'atiq', 2, 3, 4, 5, 7, 8, 9]


In [38]:
del (s[0:2])
print(s)

[2, 3, 4, 5, 7, 8, 9]


In [39]:
del (s[-1])

In [43]:
s.pop()
s

[2, 3, 4]

In [44]:
s.clear()
s

[]

In [46]:
s = [1,2,3,4,5]
c = [6,7,8,9,9]
print(s + c)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 9]


In [49]:
s * 2
print(s)

[1, 2, 3, 4, 5]


In [50]:
1 in s

True

In [51]:
8 in s

False

In [52]:
len(s)

5

In [53]:
min(s)

1

In [54]:
max(s)

5

In [55]:
sorted(s,reverse=True)

[5, 4, 3, 2, 1]

In [57]:
s.sort(reverse=True)

In [58]:
s

[5, 4, 3, 2, 1]

In [59]:
for i in s:
    print(i)

5
4
3
2
1


In [60]:
s.index(3)

2

In [61]:
a = 'hello my name is atiq'
a

'hello my name is atiq'

In [78]:
a = 'my name is atiq khan'
a.title()

'My Name Is Atiq Khan'

In [83]:
s = [1,1,2,2,3,3,4,4,5,5]
l = []
for i in s:
    if i not in l:
        l.append(i)
print(l)

[1, 2, 3, 4, 5]


In [84]:
a = 'hello my name is atiq'
print(a.split())
l = []
for i in a.split():
    print(i.capitalize())
    l.append(i.capitalize())
print(' '.join(l))

['hello', 'my', 'name', 'is', 'atiq']
Hello
My
Name
Is
Atiq
Hello My Name Is Atiq


In [85]:
a = [1,2,1,2,3,4,3,4]
a

[1, 2, 1, 2, 3, 4, 3, 4]

In [87]:
l = []
for i in a:
    if i not in l:
        l.append(i)
print(l)

[1, 2, 3, 4]


In [90]:
a = ()
print(a)

()


In [91]:
a = (1,2,'atiq',True,1.1)
a

(1, 2, 'atiq', True, 1.1)

In [92]:
a = (1,2,3,4,5,6,7)
a

(1, 2, 3, 4, 5, 6, 7)

In [93]:
a[0]

1

In [94]:
a[-1]

7

In [95]:
a[0:2]

(1, 2)

In [96]:
a[:-2]

(1, 2, 3, 4, 5)

In [97]:
a[::-1]

(7, 6, 5, 4, 3, 2, 1)

In [98]:
a

(1, 2, 3, 4, 5, 6, 7)

In [102]:
a = ('hello',)
print(type(a))

<class 'tuple'>


In [103]:
a = tuple('hello')
a

('h', 'e', 'l', 'l', 'o')

In [104]:
a[0]=12
a

TypeError: 'tuple' object does not support item assignment

In [105]:
del [1]

SyntaxError: cannot delete literal (830216045.py, line 1)

In [106]:
del (a)

In [108]:
a = (1,2,3,4,5,6,7)
a

(1, 2, 3, 4, 5, 6, 7)

In [109]:
a[0]

1

In [112]:
for i in a:
    print(i)

1
2
3
4
5
6
7


In [113]:
b = (1,2,3,4,5,6)
a + b

(1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6)

In [115]:
a * 2

(1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7)

In [117]:
1 not in a

False

In [118]:
len(a)

7

In [119]:
min(a)

1

In [120]:
max(a)

7

In [122]:
sorted(a,reverse=True)

[7, 6, 5, 4, 3, 2, 1]

In [1]:
a = {}
print(type(a))

<class 'dict'>


In [2]:
a = set()
print(type(a))

<class 'set'>


In [4]:
a = {1,2,3,4,5,6}
a

{1, 2, 3, 4, 5, 6}

In [5]:
a = {1,2,3,4,5,'hello',True}
a

{1, 2, 3, 4, 5, 'hello'}

In [6]:
a = {1,1,2,2,3,3}
a

{1, 2, 3}

In [7]:
a={[1,2,3],'hello'}
a

TypeError: unhashable type: 'list'

In [8]:
a = {(1,2,3,4),'ji'}
a

{(1, 2, 3, 4), 'ji'}

In [9]:
a = {1,2,3,4,5}
a[0]

TypeError: 'set' object is not subscriptable

In [10]:
a[0:1]

TypeError: 'set' object is not subscriptable

In [11]:
a = {1,2,3,{1,2,3,4}}
a

TypeError: unhashable type: 'set'

In [12]:
a = {1,2,3,4,5}
a

{1, 2, 3, 4, 5}

In [13]:
list(a)

[1, 2, 3, 4, 5]

In [ ]:
a1 = list(a)

In [20]:
a1[0]=100

In [22]:
a = set(a1)

In [23]:
a

{2, 3, 4, 5, 100}

In [24]:
a = {1,2,3,4,5,6,7,8}
a

{1, 2, 3, 4, 5, 6, 7, 8}

In [26]:
a.add(9)
a

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [27]:
a.remove(9)

In [32]:
a.pop()

3

In [33]:
a = {1,2,3,4,5,6}
b = {3,4,5,6,7}
a.union(b)

{1, 2, 3, 4, 5, 6, 7}

In [34]:
a.intersection(b)

{3, 4, 5, 6}

In [35]:
a.issubset(b)

False

In [37]:
a.isdisjoint(b)

False

In [38]:
a.difference(b)

{1, 2}

In [39]:
a.symmetric_difference(b)

{1, 2, 7}

In [41]:
d = {}
d

{}

In [42]:
d = {'Name':'Atiq','Age':21,'From':'Bannu','School':'Islamia'}
d

{'Name': 'Atiq', 'Age': 21, 'From': 'Bannu', 'School': 'Islamia'}

In [43]:
d1 = {[1,2,3]:'atiq'}
d1

TypeError: unhashable type: 'list'

In [44]:
d2 = {'Name':'Atiq','Age':21,'Name':'khan'}
d2

{'Name': 'khan', 'Age': 21}

In [45]:
d3 = {'Name':'Atiq','Age':21,'from':'Bannu','marks':{'math':20,'Science':30,'Eng':22}}
d3

{'Name': 'Atiq',
 'Age': 21,
 'from': 'Bannu',
 'marks': {'math': 20, 'Science': 30, 'Eng': 22}}

In [46]:
d3['Name']

'Atiq'

In [48]:
d3['Age']

21

In [49]:
d3['marks']['Eng']

22

In [50]:
d3['Name']='Hadi'
print(d3)

{'Name': 'Hadi', 'Age': 21, 'from': 'Bannu', 'marks': {'math': 20, 'Science': 30, 'Eng': 22}}


In [51]:
d3['marks']['Eng']=11
print(d3)

{'Name': 'Hadi', 'Age': 21, 'from': 'Bannu', 'marks': {'math': 20, 'Science': 30, 'Eng': 11}}


In [52]:
d3['Language']='Pashto'
print(d3)

{'Name': 'Hadi', 'Age': 21, 'from': 'Bannu', 'marks': {'math': 20, 'Science': 30, 'Eng': 11}, 'Language': 'Pashto'}


In [56]:
del (d)
print(d1)

NameError: name 'd' is not defined

In [57]:
del d3['from']
print(d3)

{'Name': 'Hadi', 'Age': 21, 'marks': {'math': 20, 'Science': 30, 'Eng': 11}, 'Language': 'Pashto'}


In [1]:
def grret():
    return 'hello world'
grret()

'hello world'

In [3]:
def add(a,b):
    return a +b
add(1,2)

3

In [4]:
add(3,3)

6

In [9]:
def max_num(a,b,c):
    if a > b and a > c:
        return a
    elif b > a and b > c:
        return b
    else:
        return c

In [10]:
result = max_num(20,30,40)
print('The Maximum nuber is ',result)

The Maximum nuber is  40


In [18]:
def vovals(s):
    vovals = 'aeiouAEIOU'
    count = 0
    for char in s:
        if char in s:
            count +=1
    return count

In [19]:
a ='hello how are you'
vovals(a)

17

In [22]:
def volol(s):
    volol='aeiouAEIOU'
    count = 0
    for char in s:
        if char in volol:
            count += 1
    return count

In [23]:
a = 'Hello My NamE is AtIq'
volol(a)

7

In [26]:
def string(s):
    return s[::-1]

In [27]:
string(a)

'qItA si EmaN yM olleH'

In [32]:
def sum_list(lst):
    return sum(lst)

In [33]:
a = [1,2,3,4]
sum_list(a)

10

In [ ]:
def palindrome(s):
    plam = ''

In [1]:
import pandas as  pd

In [1]:
import numpy as np

In [2]:
a = np.arange(1,10)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a=np.array([[1,2,3,4]])

In [9]:
a

array([[1, 2, 3, 4]])

In [10]:
a.ndim

2

np.int64(1)

In [15]:
a = np.arange(1,10)

In [16]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.newaxis

In [19]:
a

In [2]:
# here we will write a function the will take input as ineger and will tell it is an even or odd
def ev_od(inp):
    if inp %2==0:
        return 'even'
    else:
        return 'odd'

In [15]:
# hhere we will write a function that will tell that in the string how many vowles are there
def vovles(inp):
    volol = 'aeiouAEIOU'
    count = 0
    for char in inp:
            if char in volol:
                count += 1
    return count

In [16]:
vovles('atiq')

2

In [19]:
# here we will write a function that will take a string as input and return the reveser of the string
def reverse_str(string):
    return string[::-1]

In [20]:
reverse_str('atiq')

'qita'

In [21]:
def sum_list(list):
    return sum(list)

In [22]:
a = [1,2,3,4]
sum_list(a)

10

In [23]:
sum_list([1,2,3,4,5,6])

21

In [27]:
def palidrome_func(word):
    word.lower()
    return word == word[::-1]

In [30]:
palidrome_func('pythn')

False

In [31]:
def count_word(sentence):
    sentence == sentence.split()
    return len(sentence)

In [32]:
count_word('hello my name is atiq')

21

In [33]:
def anagram(str1,str2):
    str1 = str1.replace(' ','')
    str2 = str2.replace(' ', '')
    
    return sorted(str1) == sorted(str2)

In [35]:
anagram('hello','olleh')

True

In [36]:
anagram('atiq','qita')

True

In [37]:
anagram('khan','atiq')

False

In [40]:
def multi_lis(num):
    product = 1
    for i in num:
        product *= i
    return product

In [42]:
multi_lis([1,2,3,4])

24

In [45]:
def eve_lis(list):
    return [num for num in list if num %2==0]

In [46]:
eve_lis([1,2,3,4])

[2, 4]

In [51]:
def grade_score(score):
    if score >= 90:
        return 'A'
    elif score <= 50:
        return 'B'
    else:
        return 'C'

In [52]:
grade_score(51)

'C'

In [ ]:
def remove_dup(lst):
    return lst.d